# Generated by Django 2.1.3 on 2018-11-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=128, verbose_name='Origin')),
                ('destination', models.CharField(max_length=128, verbose_name='Destination')),
                ('departure', models.DateTimeField(verbose_name='Departure')),
                ('arrival', models.DateTimeField(verbose_name='Arrival')),
                ('available_seats', models.IntegerField(verbose_name='Available Seats')),
            ],
        ),
    ]
