# Generated by Django 2.1.3 on 2018-11-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='available_seats',
            field=models.PositiveIntegerField(verbose_name='Available Seats'),
        ),
    ]
